source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HealthCheck_Example', :exclusive => true do
  pod 'HealthCheck', :path => '../'
end

target 'HealthCheck_Tests', :exclusive => true do
  pod 'HealthCheck', :path => '../'

  
end
